#!/bin/bash
# https://youtu.be/emhouufDnB4?t=2260
freespace=$(df -h| grep -E "\/$" | awk '{print $4}')
greentext="\033[32m"
blod="\033[1m"
normal="\033[0m"
logdate=$(date +"%Y%m%d") # space 注意！
logfile="$logdate"_report.log

echo -e $blod"Quikc system report for "$greentext"$HOSTNAME"$normal
printf "\tSystem type:\t%s\n" $MACHTYPE
printf "\tBash Version:\t%s\n" $BASH_VERSION
printf "\tFree Space:\t%s\n" $freespace
printf "\tFiles in dir:\t%s\n" $(ls | wc -l)
printf "\tGenerated on:\t%s\n" $(date +"%m/%d/%y")

echo -e $greentext"A summary of this info has been saved to $logfile"$normal

cat <<- EOF > $logfile
        This report was automatically generated by my Bash Script.
        It contains a brief summary of some system infomation.
EOF
